<?xml version="1.0" encoding="utf-8"?><Database Name="QUANLYBANGDIA" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=WIN-C60KFQ1CQ4H\SQLEXPRESS;Initial Catalog=QUANLYBANGDIA;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QUANLYBANGDIAConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BANGDIA" Member="BANGDIAs">
    <Type Name="BANGDIA">
      <Column Name="MABD" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENBD" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HANGSANXUAT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="TINHTRANG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ma_THELOAI_Bang_Dia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SOLUONGTON" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HINH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="BANGDIA_CHITIETHOADON" Member="CHITIETHOADONs" ThisKey="MABD" OtherKey="MABD" Type="CHITIETHOADON" />
      <Association Name="TheLoai_BANGDIA" Member="TheLoai" ThisKey="ma_THELOAI_Bang_Dia" OtherKey="MaTheLoai" Type="TheLoai" IsForeignKey="true" />
      <Association Name="HANGSANXUAT_BANGDIA" Member="HANGSANXUAT1" ThisKey="HANGSANXUAT" OtherKey="MaHANGSANXUAT" Type="HANGSANXUAT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TheLoai" Member="TheLoais">
    <Type Name="TheLoai">
      <Column Name="MaTheLoai" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTheLoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TheLoai_BANGDIA" Member="BANGDIAs" ThisKey="MaTheLoai" OtherKey="ma_THELOAI_Bang_Dia" Type="BANGDIA" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETHOADON" Member="CHITIETHOADONs">
    <Type Name="CHITIETHOADON">
      <Column Name="MAHD" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MABD" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SONGAYDUOCMUON" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TINHTRANG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="BANGDIA_CHITIETHOADON" Member="BANGDIA" ThisKey="MABD" OtherKey="MABD" Type="BANGDIA" IsForeignKey="true" />
      <Association Name="HOADON_CHITIETHOADON" Member="HOADON" ThisKey="MAHD" OtherKey="MAHD" Type="HOADON" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HANGSANXUAT" Member="HANGSANXUATs">
    <Type Name="HANGSANXUAT">
      <Column Name="MaHANGSANXUAT" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenHANGSANXUAT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="HANGSANXUAT_BANGDIA" Member="BANGDIAs" ThisKey="MaHANGSANXUAT" OtherKey="HANGSANXUAT" Type="BANGDIA" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="MAHD" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGAYLAP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MAKH" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="HOADON_CHITIETHOADON" Member="CHITIETHOADON" ThisKey="MAHD" OtherKey="MAHD" Type="CHITIETHOADON" Cardinality="One" />
      <Association Name="KHACHHANG_HOADON" Member="KHACHHANG" ThisKey="MAKH" OtherKey="MAKH" Type="KHACHHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MAKH" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DIENTHOAI" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Pass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="KHACHHANG_HOADON" Member="HOADONs" ThisKey="MAKH" OtherKey="MAKH" Type="HOADON" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MANV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CMND" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DIENTHOAI" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="NHANVIEN_TAIKHOAN" Member="TAIKHOANs" ThisKey="MANV" OtherKey="MANV" Type="TAIKHOAN" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="TENTAIKHOAN" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MATKHAU" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="LOAITK" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="NHANVIEN_TAIKHOAN" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>